// Array of random, funny loading messages
const loadingMessages = [
  "Optimizing flux capacitor...",
  "Feeding the unicorns...",
  "Reticulating splines...",
  "Summoning ancient loading spirits...",
  "Petting virtual cats...",
  "Gathering enough motivation...",
  "Folding space-time fabric...",
  "Starting hamster wheel...",
  "Pretending to load faster...",
  "Sharpening pixels...",
  "Chasing wild bugs...",
  "Calibrating infinite improbability drive...",
  "Tuning time machine...",
  "Counting to infinity... again.",
  "Synchronizing with the quantum realm...",
  "Asking for directions to the internet...",
  "Reheating leftover code...",
  "Polishing keyboard shortcuts...",
  "Consulting with an AI guru...",
  "Calculating the meaning of life...",
  "Rearranging the bits...",
  "Stretching server muscles...",
  "Training the neural hamster...",
  "Generating random gibberish...",
  "Knitting a digital scarf...",
  "Collecting virtual socks...",
  "Rewriting reality... please wait.",
  "Reversing polarity of the neutron flow...",
  "Befriending a lost packet...",
  "Translating binary to Klingon...",
  "Rewiring the matrix...",
  "Staring intently at the code...",
  "Locating the elusive semicolon...",
  "Convincing electrons to cooperate...",
  "Charging flux batteries...",
  "Duct-taping the cloud together...",
  "Tickling the RAM...",
  "Applying extra glue to the internet...",
  "Taming wild algorithms...",
  "Spinning electrons in reverse...",
  "Cooking up a solution...",
  "Aligning planets for better performance...",
  "Waking up the quantum computer...",
  "Cloning the cloud...",
  "Simulating simulated simulations...",
  "Holding hands with Schrödinger’s cat...",
  "Painting the pixels by hand...",
  "Running with scissors... carefully.",
  "Warming up the space lasers...",
  "Cross-referencing infinite scroll...",
  "Filling the internet tubes with data...",
  "Politely asking for server permission...",
  "Recharging crystal ball...",
  "Baking 1s and 0s...",
  "Interrogating suspicious cookies...",
  "Unraveling the spaghetti code...",
  "Sending requests to a parallel universe...",
  "Accidentally dividing by zero...",
  "Convincing AI to take a coffee break...",
  "Untangling the web of lies...",
  "Organizing code like Marie Kondo...",
  "Consulting the algorithmic oracles...",
  "Bribing electrons with more power...",
  "Gently whispering to the database...",
  "Inserting humor module...",
  "Restocking the virtual vending machine...",
  "Cloning bits... please don’t blink.",
  "Reassembling the ones and zeros...",
  "Bargaining with time-travel paradoxes...",
  "Decoding ancient hieroglyphs...",
  "Generating wormholes for faster access...",
  "Synchronizing with an alternate reality...",
  "Consulting the space chickens...",
  "Calming angry packets...",
  "Waiting for the coffee to brew...",
  "Aligning bits with cosmic forces...",
  "Reassuring the server it’s doing great...",
  "Folding paper airplanes from HTML...",
  "Consulting the magic eight-ball...",
  "Summoning rubber duck for debugging...",
  "Wrapping code in bubble wrap...",
  "Organizing bits alphabetically...",
  "Polishing virtual sunglasses...",
  "Translating server logs into ancient runes...",
  "Defragging your imagination...",
  "Lubricating the hamster wheel...",
  "Gathering mana from the server gods...",
  "Convincing the cloud it’s not a storm...",
  "Sharpening CSS skills with ninja stars...",
  "Running the hamster faster...",
  "Unlocking the secret of the universe...",
  "Shooting lasers at rogue semicolons...",
  "Sorting the chaos theory...",
  "Peeling the layers of abstraction...",
  "Rerouting the flux matrix...",
  "Tuning the quantum antenna...",
  "Unlocking all the cheat codes...",
  "Overclocking the imagination...",
  "Sneezing on the code... sorry!",
  "Learning to count beyond 10...",
  "Teleporting bits to the right place...",
  "Balancing on a digital tightrope...",
  "Herding digital cats...",
  "Charging your virtual reality...",
  "Politely asking the data to cooperate...",
  "Lubricating the gears of the internet...",
  "Synchronizing the pixels with reality...",
  "Tickling the code into submission...",
  "Tethering the bits to reality...",
  "Planting digital trees...",
  "Waking up the internet gremlins...",
  "Turning off the internet’s airplane mode...",
  "Decoding the encryption of the universe...",
];

// Function to display a random message
function showRandomMessage() {
  const messageElement = document.getElementById("loadingMessage");
  const randomIndex = Math.floor(Math.random() * loadingMessages.length);
  messageElement.textContent = loadingMessages[randomIndex];
}

// Change message every 2.5 seconds
setInterval(showRandomMessage, 4000);
